spring.application.name=backend
spring.cache.type=caffeine
spring.cache.cache-names=initDashboard
spring.cache.caffeine.spec=maximumSize=32,expireAfterWrite=24h
app.athena.region=${AWS_REGION}
app.athena.database=flight_analytics
app.athena.workgroup=${ATHENA_WORKGROUP:primary}
app.athena.output-location=${ATHENA_OUTPUT_LOCATION}
app.athena.query-timeout=${ATHENA_QUERY_TIMEOUT:30s}
app.athena.sleep = 1000
